sudo: false

language: php

php:
    - 7.2
    - 7.3

cache:
    directories:
        - $HOME/.composer/cache

env:
    global:
        - SYMFONY_ENV=test

before_script:
    - echo 'date.timezone = America/Vancouver' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - composer install -n -o

script:
    - ./vendor/bin/phpunit
