imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

monolog:
    use_microseconds: false
    handlers:
        main:
            type: rotating_file
            max_files: 10
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: warning
            channels: ['!event', '!doctrine', '!console', '!translation']
        console:
            type:   console
            channels: ['!event', '!doctrine', '!console', '!translation']
