# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       [ ROLE_ADMIN, ROLE_BLOG_ADMIN, ROLE_COMMENT_ADMIN, ROLE_CONTENT_ADMIN ]
        ROLE_BLOG_ADMIN: ROLE_USER
        ROLE_COMMENT_ADMIN: ROLE_USER
        ROLE_CONTENT_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout_on_user_change: true

            remember_me:
                secret: '%secret%'
                lifetime: 2419200 # 28 days in seconds.
                path: '%router.request_context.base_url%'
                domain: '%router.request_context.host%'
                secure: '%secure_cookies%'

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/feedback, roles: [ ROLE_USER, IS_AUTHENTICATED_ANONYMOUSLY ]}
        - { path: ^/admin/comment/post, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
